name: Nightly Tests

on:
  schedule:
    # Runs every day at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # allows manual trigger too

jobs:
  nightly-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [20.x, 22.x, 24.x, 25.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      # ----------------------------
      # Cache fixture node_modules
      # ----------------------------
      - name: Cache fixture node_modules
        uses: actions/cache@v4
        with:
          path: |
            fixtures/combined/node_modules
          key: ${{ runner.os }}-fixtures-node-modules-${{ hashFiles('fixtures/**/package.json', 'fixtures/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-fixtures-node-modules-

      - run: yarn install --frozen-lockfile
      - run: yarn build

      # ----------------------------
      # Setup fixtures
      # ----------------------------
      - name: combined fixtures
        working-directory: ./fixtures/combined
        run: yarn install --production

      - name: Run tests
        run: yarn test
